#! /bin/bash

iptables -F
iptables -X
iptables -t nat -F
iptables -t nat -X
iptables -t mangle -F
iptables -t mangle -X
iptables -P INPUT ACCEPT
iptables -P OUTPUT ACCEPT
iptables -P FORWARD ACCEPT
iptables -L

echo "reset iptables"

cp /root/vmReset/sshd_config /etc/ssh/sshd_config
service ssh restart

echo "restarted ssh"

rm -rf /home/deploy/src

echo "removed old code"
echo "reset root pass"
passwd

